// scrapycw/frontend/src/App.vue
<template>
  <div id="app">
    <layout-header></layout-header>
    <router-view/>  
  </div>
</template>

<script>
import LayoutHeader from "@/components/LayoutHeader"
export default {
  name: "App",
  components: { LayoutHeader },
}
</script>

<style scoped> 
#app {
  height: 100%;
  overflow-y: hidden;
}
</style>

// scrapycw/frontend/src/App.tsx
import style from '@/App.module.css';
import { Header } from '@/components/layout';
import Main from '@/components/Main';
import { BrowserRouter as Router } from "react-router-dom";


const App = () => (
    <div className={ style.app }>
        <Router>
            <Header />
            <Main className={ style.main }/>
        </Router>
    </div>
);

export default App;
